/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'artSupplies' : null } |
  { 'schoolSupplies' : null } |
  { 'writing' : null } |
  { 'paper' : null } |
  { 'officeEssentials' : null };
export interface Order {
  'customerName' : string,
  'status' : OrderStatus,
  'orderId' : OrderId,
  'totalAmount' : bigint,
  'address' : string,
  'timestamp' : Time,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'pending' : null } |
  { 'dispatched' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Product {
  'id' : ProductId,
  'stockQuantity' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'price' : bigint,
}
export type ProductId = bigint;
export type Time = bigint;
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [string, string, Category, bigint, bigint, string],
    Product
  >,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'placeOrder' : ActorMethod<
    [string, string, string, Array<OrderItem>, bigint],
    Order
  >,
  'seedProducts' : ActorMethod<[], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [ProductId, string, string, Category, bigint, bigint, string],
    Product
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];